In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Labelled.csv')

df.head()

,author,last_updated,title,review,rating,app_version,net_helpfulness,helpfulness_count,sentiment,intent,confidence,reason
0,brucruzg008009,2026-04-07T21:37:16-07:00,Terrible,I made an account last year December and not e...,1,12.6.1,0,0,negative,complaint,high,The review expresses strong dissatisfaction an...
1,Jawsh R,2026-04-07T21:35:48-07:00,Delete this,Zero live operator to deal with problems that ...,1,12.6.1,0,0,negative,complaint,high,The review expresses frustration and a complai...
2,Kay Nason,2026-04-07T16:56:52-07:00,Secure,Love it as it makes it easier to communicate w...,5,12.6.1,0,0,positive,praise,high,The review expresses satisfaction and apprecia...
3,Aadfwtwnwnwk,2026-04-07T10:55:35-07:00,Error,After updating I can’t open chats,5,12.6.1,0,0,negative,bug_report,high,The review describes a functional issue after ...
4,abdul wagood,2026-04-07T10:24:25-07:00,The program dose not work,I do wonder the program was working very well ...,1,12.6.1,0,0,negative,complaint,high,The review expresses dissatisfaction and a fun...

In [3]:
df['intent'].value_counts()

intent
complaint          2932
praise             2248
bug_report          460
feature_request     250
troll               151
question             75
Name: count, dtype: int64

In [4]:
# selected_data = df[df['confidence'] == 'high']
selected_data = df

# Print the selected data
selected_data

,author,last_updated,title,review,rating,app_version,net_helpfulness,helpfulness_count,sentiment,intent,confidence,reason
0,brucruzg008009,2026-04-07T21:37:16-07:00,Terrible,I made an account last year December and not e...,1,12.6.1,0,0,negative,complaint,high,The review expresses strong dissatisfaction an...
1,Jawsh R,2026-04-07T21:35:48-07:00,Delete this,Zero live operator to deal with problems that ...,1,12.6.1,0,0,negative,complaint,high,The review expresses frustration and a complai...
2,Kay Nason,2026-04-07T16:56:52-07:00,Secure,Love it as it makes it easier to communicate w...,5,12.6.1,0,0,positive,praise,high,The review expresses satisfaction and apprecia...
3,Aadfwtwnwnwk,2026-04-07T10:55:35-07:00,Error,After updating I can’t open chats,5,12.6.1,0,0,negative,bug_report,high,The review describes a functional issue after ...
4,abdul wagood,2026-04-07T10:24:25-07:00,The program dose not work,I do wonder the program was working very well ...,1,12.6.1,0,0,negative,complaint,high,The review expresses dissatisfaction and a fun...
...,...,...,...,...,...,...,...,...,...,...,...,...
6111,King A.P,2026-03-17T18:56:54-07:00,My personal review,"Chris gave an excellent, marvelous, and fantas...",4,26.11.1,0,0,positive,praise,high,The review expresses clear satisfaction and pr...
6112,Ewpayreonsux,2026-03-17T18:52:21-07:00,Lists have disappeared,This used to be a great app but it no longer l...,1,26.11.1,0,0,negative,complaint,high,The review expresses frustration over a functi...
6113,Norman_g,2026-03-17T18:21:20-07:00,Uninstalled after years of use,The added AI and I removed the app from my phone.,1,26.11.1,1,1,negative,complaint,low,"Short review with implied dissatisfaction, but..."
6114,Eefieee,2026-03-17T18:11:33-07:00,Inconsistent and unreliable real-time reporting,"For NYC public transit, the reporting is unrel...",2,26.11.1,0,0,negative,complaint,high,The review expresses clear dissatisfaction wit...
6115,Serrano's plumbing service's,2026-03-17T17:39:54-07:00,I love Google Maps !!,Google has been the center of my growth and I ...,5,26.11.1,0,0,positive,praise,high,Enthusiastic praise with clear positive sentim...

In [5]:
dataset = selected_data.drop(['app_version', 'last_updated', 'author', 'confidence', 'reason'], axis=1)

dataset

,title,review,rating,net_helpfulness,helpfulness_count,sentiment,intent
0,Terrible,I made an account last year December and not e...,1,0,0,negative,complaint
1,Delete this,Zero live operator to deal with problems that ...,1,0,0,negative,complaint
2,Secure,Love it as it makes it easier to communicate w...,5,0,0,positive,praise
3,Error,After updating I can’t open chats,5,0,0,negative,bug_report
4,The program dose not work,I do wonder the program was working very well ...,1,0,0,negative,complaint
...,...,...,...,...,...,...,...
6111,My personal review,"Chris gave an excellent, marvelous, and fantas...",4,0,0,positive,praise
6112,Lists have disappeared,This used to be a great app but it no longer l...,1,0,0,negative,complaint
6113,Uninstalled after years of use,The added AI and I removed the app from my phone.,1,1,1,negative,complaint
6114,Inconsistent and unreliable real-time reporting,"For NYC public transit, the reporting is unrel...",2,0,0,negative,complaint
6115,I love Google Maps !!,Google has been the center of my growth and I ...,5,0,0,positive,praise

In [6]:
dataset['text'] = (
    "Rating: " + dataset['rating'].astype(str) +
    ". Title: " + dataset['title'] +
    ". Review: " + dataset['review']
)

dataset

,title,review,rating,net_helpfulness,helpfulness_count,sentiment,intent,text
0,Terrible,I made an account last year December and not e...,1,0,0,negative,complaint,Rating: 1. Title: Terrible. Review: I made an ...
1,Delete this,Zero live operator to deal with problems that ...,1,0,0,negative,complaint,Rating: 1. Title: Delete this. Review: Zero li...
2,Secure,Love it as it makes it easier to communicate w...,5,0,0,positive,praise,Rating: 5. Title: Secure. Review: Love it as i...
3,Error,After updating I can’t open chats,5,0,0,negative,bug_report,Rating: 5. Title: Error. Review: After updatin...
4,The program dose not work,I do wonder the program was working very well ...,1,0,0,negative,complaint,Rating: 1. Title: The program dose not work. R...
...,...,...,...,...,...,...,...,...
6111,My personal review,"Chris gave an excellent, marvelous, and fantas...",4,0,0,positive,praise,Rating: 4. Title: My personal review. Review: ...
6112,Lists have disappeared,This used to be a great app but it no longer l...,1,0,0,negative,complaint,Rating: 1. Title: Lists have disappeared. Revi...
6113,Uninstalled after years of use,The added AI and I removed the app from my phone.,1,1,1,negative,complaint,Rating: 1. Title: Uninstalled after years of u...
6114,Inconsistent and unreliable real-time reporting,"For NYC public transit, the reporting is unrel...",2,0,0,negative,complaint,Rating: 2. Title: Inconsistent and unreliable ...
6115,I love Google Maps !!,Google has been the center of my growth and I ...,5,0,0,positive,praise,Rating: 5. Title: I love Google Maps !!. Revie...

In [7]:
clean_df = dataset.drop(['title', 'review', 'rating', 'net_helpfulness', 'helpfulness_count'], axis=1)

clean_df

     sentiment      intent                                               text
0     negative   complaint  Rating: 1. Title: Terrible. Review: I made an ...
1     negative   complaint  Rating: 1. Title: Delete this. Review: Zero li...
2     positive      praise  Rating: 5. Title: Secure. Review: Love it as i...
3     negative  bug_report  Rating: 5. Title: Error. Review: After updatin...
4     negative   complaint  Rating: 1. Title: The program dose not work. R...
...        ...         ...                                                ...
6111  positive      praise  Rating: 4. Title: My personal review. Review: ...
6112  negative   complaint  Rating: 1. Title: Lists have disappeared. Revi...
6113  negative   complaint  Rating: 1. Title: Uninstalled after years of u...
6114  negative   complaint  Rating: 2. Title: Inconsistent and unreliable ...
6115  positive      praise  Rating: 5. Title: I love Google Maps !!. Revie...

[6116 rows x 3 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

sentiment_encoder = LabelEncoder()
intent_encoder = LabelEncoder()

clean_df['sentiment_label'] = sentiment_encoder.fit_transform(clean_df['sentiment'])
clean_df['intent_label'] = intent_encoder.fit_transform(clean_df['intent'])

In [9]:
min_samples = 2

valid_classes = clean_df["sentiment"].value_counts()
valid_classes = valid_classes[valid_classes >= min_samples].index

df = clean_df[clean_df["sentiment"].isin(valid_classes)]

df['sentiment'].value_counts()

sentiment
negative    3196
positive    2333
neutral      392
mixed        195
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df['sentiment_label']
)

In [11]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

X_train = model.encode(train_df["text"].tolist(), show_progress_bar=True)
X_val = model.encode(val_df["text"].tolist(), show_progress_bar=True)

d:\My Portfolio\GitHub\test\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10002.86it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 153/153 [00:26<00:00,  5.87it/s]
Batches: 100%|██████████| 39/39 [00:06<00:00,  6.22it/s]

In [12]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_smoted, y_train_smoted = smote.fit_resample(X_train, train_df["sentiment_label"])

In [13]:
from sklearn.linear_model import LogisticRegression

sentiment_model = LogisticRegression(max_iter=2000)

sentiment_model.fit(X_train, train_df["sentiment_label"])

LogisticRegression(max_iter=2000)

In [14]:
intent_model = LogisticRegression(max_iter=2000)

intent_model.fit(X_train, train_df["intent_label"])

LogisticRegression(max_iter=2000)

In [15]:
from sklearn.metrics import classification_report

sent_pred = sentiment_model.predict(X_val)

print(classification_report(val_df["sentiment_label"], sent_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        39
           1       0.89      0.94      0.91       640
           2       0.71      0.28      0.40        78
           3       0.84      0.92      0.88       467

    accuracy                           0.86      1224
   macro avg       0.61      0.54      0.55      1224
weighted avg       0.83      0.86      0.84      1224

d:\My Portfolio\GitHub\test\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\My Portfolio\GitHub\test\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\My Portfolio\GitHub\test\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [16]:
def predict_review(text):
    embedding = model.encode([text])

    sentiment = sentiment_model.predict(embedding)
    intent = intent_model.predict(embedding)

    return (
        sentiment_encoder.inverse_transform(sentiment)[0],
        intent_encoder.inverse_transform(intent)[0]
    )

In [17]:
predict_review("Rating: 5. Title: Honest Review. Review: UI is so messy I can't see anything on the main screen, but the app does accomplish what it advertised and made my life simpler.")

('negative', 'complaint')